// Dead-Lead Revival — proof & cohort API
//
// GET  /api/revival                  → live proof summary: dead-lead pool, baseline,
//                                       and outcomes for every saved cohort
// POST /api/revival?action=cohort    → freeze current dead leads into a new cohort
//                                       body: { name?, holdoutPct? }
//
// This endpoint is read-only proof + cohort bookkeeping. It NEVER sends messages —
// outreach drafts are generated by /api/revival/run and approved via /api/drafts.

import { NextRequest } from "next/server";
import { prisma } from "@/lib/prisma";
import {
  getDeadLeads,
  getRevivalBaseline,
  getCohortOutcomes,
  createCohort,
} from "@/lib/revival";

export async function GET() {
  const [dead, baseline, cohorts] = await Promise.all([
    getDeadLeads(),
    getRevivalBaseline(),
    prisma.revivalCohort.findMany({ orderBy: { createdAt: "desc" }, take: 20 }),
  ]);

  const cohortOutcomes = await Promise.all(cohorts.map((c) => getCohortOutcomes(c.id)));

  return Response.json({
    deadCount: dead.length,
    deadPipeline: dead.reduce((sum, l) => sum + (l.pricePoint ?? 0), 0),
    baseline,
    cohorts: cohortOutcomes.filter(Boolean),
  });
}

export async function POST(req: NextRequest) {
  const { searchParams } = new URL(req.url);
  const action = searchParams.get("action") ?? "cohort";

  if (action === "cohort") {
    const body = await req.json().catch(() => ({}));
    const result = await createCohort({
      name: typeof body?.name === "string" ? body.name : undefined,
      holdoutPct: typeof body?.holdoutPct === "number" ? body.holdoutPct : undefined,
    });
    if ("error" in result) {
      return Response.json(result, { status: 400 });
    }
    return Response.json(result);
  }

  return Response.json({ error: "Invalid action" }, { status: 400 });
}
